### ISSUE TITLE
Add support for the new swagger/openapi spec 3

### ISSUE THREAD

**Issue by cguedes** [sky-uk/api-explorer#173]
https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md
https://www.openapis.org/blog/2017/03/01/openapi-spec-3-implementers-draft-released
https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/

**Comment by danielbcorreia** [comment]
Already done
