### ISSUE TITLE
Upgrade project dependencies

### ISSUE THREAD

**Issue by cguedes** [sky-uk/api-explorer#174]
**Motivation**

We have a lot of deprecated/old dependencies (e.g. react 0.14.0), and because of we can't take advantage of some features/packages.

![image](https://cloud.githubusercontent.com/assets/174127/24242817/e8af0cb2-0fb0-11e7-8700-cde3be4ff039.png)

**Comment by danielbcorreia** [comment]
Fixed

**Comment by danielbcorreia** [comment]
Fixed
