### ISSUE TITLE
Standardize request and response header names casing

### ISSUE THREAD

**Issue by danielbcorreia** [sky-uk/api-explorer#192]
This is the current state:
![image](https://user-images.githubusercontent.com/818210/35148923-10e1918e-fd0c-11e7-8b71-78539c4a0e9e.png)

We should have a process before rendering to capitalize the header names, such as:
content-type -> Content-Type
accept -> Accept

These response header names are returned in lowercase from fetch, and as such we can't preserve the original casing.

**Comment by MarcosAndre** [comment]
Done.
<img width="866" alt="screen shot 2018-02-01 at 09 27 40" src="https://user-images.githubusercontent.com/1064877/35672659-202e8ebe-0737-11e8-8d8d-41ed44eb9eaf.png">
