### ISSUE TITLE
Home Page loads incorrectly if not on host root

### ISSUE THREAD

**Issue by miguelmcorreia** [sky-uk/api-explorer#348]
If the APIExplorer index is not set on the root of the host, then the Home Summary page will not load correctly.
It will only load if the user clicks the `Home` button.

See attached gif for scenario
![api-explorer-routing-bug](https://user-images.githubusercontent.com/24386755/89815312-796e1680-db3c-11ea-99e7-68502049237d.gif)

**Comment by MarcosAndre** [comment]
Solved. To avoid it use the setBasePath("/api/explorer") on the APIExplorer DSL configuration.
